language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
notifications:
  email: false
node_js:
  - "node"
install:
  - npm install
script:
  - npm run validate
after_success:
  - npx codecov
branchs:
  only: master
